
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxtbdjyjlltxzhjwpwhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4dGJkanlqbGx0eHpoandwd2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDg2MTIsImV4cCI6MjA2NjM4NDYxMn0.xCt5SCUmHJuBNydosU48qdnmW_viaGYMSxp4DKH3yRg";

// Create the Supabase client with additional configuration
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
  }
);
