// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxtbdjyjlltxzhjwpwhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4dGJkanlqbGx0eHpoandwd2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDg2MTIsImV4cCI6MjA2NjM4NDYxMn0.xCt5SCUmHJuBNydosU48qdnmW_viaGYMSxp4DKH3yRg";

// Create the Supabase client with additional configuration
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'pkce', // Use PKCE for better security
      debug: true // Enable debug logging
    },
    global: {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
      },
    },
  }
);

// Helper function to test a promise with timeout
const withTimeout = <T,>(
  promise: Promise<T>,
  timeout: number,
  errorMessage: string
): Promise<T> => {
  return new Promise((resolve, reject) => {
    const timeoutId = setTimeout(() => {
      reject(new Error(errorMessage));
    }, timeout);

    promise
      .then((result) => {
        clearTimeout(timeoutId);
        resolve(result);
      })
      .catch((error) => {
        clearTimeout(timeoutId);
        reject(error);
      });
  });
};

// Basic connectivity test
export const testBasicConnectivity = async () => {
  console.log('Testing basic connectivity to Supabase...');
  
  try {
    // Test 1: Basic ping to the Supabase URL
    console.log('1. Testing basic connectivity...');
    const response = await fetch(SUPABASE_URL, {
      method: 'OPTIONS', // Use OPTIONS for CORS preflight
      headers: {
        'Content-Type': 'application/json',
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`
      }
    });
    
    if (!response.ok) {
      console.log('Response status:', response.status, response.statusText);
      console.log('Response headers:', Object.fromEntries(response.headers.entries()));
      throw new Error(`Failed to connect to Supabase: ${response.status} ${response.statusText}`);
    }
    
    console.log('✅ Basic connectivity test passed');
    console.log('CORS Headers:', {
      'Access-Control-Allow-Origin': response.headers.get('Access-Control-Allow-Origin'),
      'Access-Control-Allow-Methods': response.headers.get('Access-Control-Allow-Methods'),
      'Access-Control-Allow-Headers': response.headers.get('Access-Control-Allow-Headers'),
    });
    
    return true;
  } catch (error) {
    console.error('Basic connectivity test failed:', error);
    throw new Error(`Connectivity test failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};

// Test function to verify Supabase connection
export const testSupabaseConnection = async () => {
  console.group('🔌 Testing Supabase Connection');
  
  try {
    // Test 1: Client Initialization
    console.log('1. Testing Supabase client initialization...');
    if (!supabase) {
      throw new Error('Supabase client failed to initialize');
    }
    console.log('✅ Supabase client initialized successfully');

    // Test 2: Basic REST API connection
    console.log('2. Testing REST API connection...');
    try {
      const { data, error } = await withTimeout(
        (async () => {
          const response = await supabase.from('puppies').select('*').limit(0);
          return response;
        })(),
        5000,
        'REST API connection timed out after 5 seconds'
      );
      
      if (error) {
        console.warn('⚠️ REST API test warning:', error.message);
        throw error;
      } else {
        console.log('✅ REST API connection successful');
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown error';
      console.warn('⚠️ REST API test warning:', errorMessage);
      throw new Error(`REST API connection failed: ${errorMessage}`);
    }

    // If we get here, all tests passed
    console.log('✅ All connection tests passed');
    
    return { 
      success: true, 
      message: 'Connection test successful!',
      timestamp: new Date().toISOString()
    };
  } catch (error) {
    console.error('❌ Connection test failed:', error);
    
    // Check for common issues
    let errorMessage = 'Connection test failed';
    let details = error instanceof Error ? error.message : 'Unknown error';
    
    if (details.includes('Failed to fetch') || details.includes('NetworkError')) {
      errorMessage = 'Network error. Please check your internet connection.';
    } else if (details.includes('timed out')) {
      errorMessage = 'Connection timed out. The server is taking too long to respond.';
    } else if (details.includes('JWT') || details.includes('apikey') || details.includes('401')) {
      errorMessage = 'Authentication error. Please check your Supabase API key.';
    } else if (details.includes('CORS') || details.includes('has been blocked by CORS policy')) {
      errorMessage = 'CORS error. Please check your Supabase CORS settings.';
    }
    
    console.error('Error details:', {
      errorMessage,
      details,
      timestamp: new Date().toISOString()
    });
    
    return { 
      success: false, 
      error: details,
      message: errorMessage,
      timestamp: new Date().toISOString()
    };
  } finally {
    console.groupEnd();
  }
};