// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhbgdrodshrmfshbmmxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoYmdkcm9kc2hybWZzaGJtbXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ4NzQ3NzMsImV4cCI6MjEwMDQ1MDc3M30.RZlT7YIopQ3RnChQ6vuhJSa1oOPKPPBxLZAF4RJC3m8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});